name: Unit Test with Jest

on:
  pull_request:
    branches: ["main", "dev"]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: ["16.x"]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Prepare Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Test project
        run: npm run test
