name: Unit Test with Jest

on:
  push:
    branches: ["deploy/#30"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  test:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: ["16.x"]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Prepare Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install & Test
        run: |
          npm ci
          npm run test
